site_name: Breeze256's Blog
site_url: https://breeze256.github.io/
site_author: Breeze256

# Contents
nav:
  - 主页: 
    - Getting Started: index.md
    - F.A.Q.:  home/F_A_Q.md
  - section1: 
    - test1: section1/test1.md
    - test2: section1/test2.md

theme: 
  name: 'material'
  language: zh
  font: 
    text: Noto Sans SC
    code: Fira Mono
  icon: 
    logo: material/star-shooting-outline
  favicon: assets/images/favicon.png
  palette:
    primary: white
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
plugins:
  - search
