site_name: Breeze256's Blog
site_url: https://breeze256.github.io/
site_author: Breeze256
repo_url: https://github.com/breeze256/breeze256.github.io
repo_name: breeze256/breeze256.github.io

# Contents
nav:
  - 主页: 
    - Getting Started: index.md
    - F.A.Q.:  home/F_A_Q.md
  - 关于: 
    - test1: about/test1.md
    - test2: about/test2.md

theme: 
  name: 'material'
  language: zh
  font: 
    text: Noto Sans SC
    code: Fira Mono
  icon: 
    logo: material/star-shooting-outline
    repo: fontawesome/brands/git-alt
  favicon: assets/images/favicon.png
  palette:
    primary: white
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
plugins:
  - search
